apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-container
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "CronJob executed"
          restartPolicy: OnFailure
